### ISSUE TITLE
Ajax Request Not Being Generated to Rails Server

### ISSUE THREAD

**Issue by tdewell** [leppert/remotipart#16]
I'm trying your gem to do AJAX based photo upload for Rails 3 project I'm working on.

I've tried getting it to work based on:

https://github.com/formasfunction/remotipart

Also tried it by trying this way:

https://github.com/formasfunction/remotipart/wiki/Getting-Remotipart-to-work-with-latest-jquery-ujs

I've gone back to using the first way, and it looks like the app uploads the file but my logs never
see a POST request.

Here aresome code fragments:

<% form_for(@entry, :html => {:multipart => true}, :remote => true ) do |f| %>

bundle list:
- remotipart (0.3.1)

Questions & Answers

-What do you mean by, it looks like the file is uploaded?

Browser tab says "loading" with a spinner for about the time it take to upload a file.

-What does Firebug say? 

hr is not defined
[Break On This Error] "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 

-Is it actually doing the AJAX call at all? 

It does not look like it.

-Does you app see a request, but just no file included?

No request in the logs.

**Comment by JangoSteve** [comment]
Hey Todd, I think the problem is that your page is using XHTML transitional, and Rails 3 and jQuery UJS are dependent upon HTML 5. You can see my article for the full scoop [explaining the role that HTML 5 plays in remote links/forms in Rails 3](http://www.alfajango.com/blog/rails-3-remote-links-and-forms/).

Try using the HTML 5 declaration at the top of your layout, by replacing this:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"> 
```

With this:

```
<html>
```

**Comment by JangoSteve** [comment]
Hey Todd, I think I figured it out. The request actually is being sent to your server, but the server is returning a 404 Nginx error, which means the request isn't making it to your rails app, which explains why it's not showing up in your app's log. If you look in the "Net" tab of Firebug, you can see the request being sent and the Nginx 404 response being received.

Because of the way IE treats requests for JS data-types from the iframe that's generated by remotipart.js, remotipart has to append the '.js' extension to the request URL so that the server knows it's a JS request.

Anyway, it seems your Nginx server is not configured to accept requests for http://tuys.seebuzz.com/entries.js (or perhaps it's checking for entries.js in the public folder and not finding it), so it is returning a 404. This is why posts without file uploads work in your form; in that case, it's submitting a POST request to /entries. Meanwhile, file uploads fail; they must submit via a hidden iframe to /entries.js, which should be going to your 'entries' action with a JS format request type.

I'd say there are two solutions. a) Fix the Nginx conf to allow for /entries.js to route to your rails app as normal, or b) change the 'data-type' of your remote form to something other than JS, maybe HTML or JSON.

**Comment by tdewell** [comment]
Steve,

It works now.  Woot!

See the nginx.conf entry for this dev server and the portion I commented out
to get remotipart working:

server {
        listen 80;
        server_name someserver.com;
        root /home/username/someserver.com/railsapp/public;

```
    # serve static content directly
    #location ~* \.(ico|jpg|gif|png|css|js|swf|html)$ {
      #if (-f $request_filename) {
        #expires max;
        #break;
      #}
    #}
    passenger_enabled on;
}
```

Much thanks for your help!

Todd

**Comment by JangoSteve** [comment]
Awesome, glad it worked out. You probably still want Nginx to server static files directly for the most part, so your ruby instances aren't spinning up for every static file request. Perhaps instead of commenting all that out, you could just remove the ".js" extension from the list of static file-type matches. So change this:

```
location ~* \.(ico|jpg|gif|png|css|js|swf|html)$ {
```

To this:

```
location ~* \.(ico|jpg|gif|png|css|swf|html)$ {
```
