### ISSUE TITLE
work with devise

### ISSUE THREAD

**Issue by l4u** [leppert/remotipart#17]
when the action requires authentication and the user is not logged in
the return is http 401. But it is not handled.

Where should the javascript code for handling 401 be added?

**Comment by JangoSteve** [comment]
Hi @l4u. Unfortunately, when using the iFrame method of uploading files (what Remotipart uses, since XHR file uploading is not allowed by browsers), the parent window is not allowed to inspect the response status of the iFrame, for security reasons. The parent window can only view the content that gets populated into the iFrame from the response.

This is a known shortcoming of the iFrame method. I'm in the process of writing up a more detailed explanation in an article. The way I get around this for now, is to return a different response (content-wise), depending on the status, and infer the status from that.

**Comment by JangoSteve** [comment]
I did some more digging around, and found that someone has come up with a solution by adding another iFrame hack to the form.js jQuery plugin. I actually like this solution, so hopefully they'll pull it in soon. As soon as they do, Remotipart should work properly with the response status of the file upload. In the meantime, perhaps apply their patch and give it a try.

https://github.com/malsup/form/pull/72

**Comment by JangoSteve** [comment]
It looks like they've pulled this into form.js, so all should be dandy. I'm going to close this ticket now, thanks for reporting this.
