### ISSUE TITLE
format attribute should be js, not .js

### ISSUE THREAD

**Issue by sohara** [leppert/remotipart#3]
I'm not sure if this gem is working for others, but for me it only worked after modifying the jquery.remotipart.js file to change all instances of '.js' to 'js'. Otherwise rails controllers wouldn't recognize the format as a valid mime type and hence no rendering occurred, just a 406 response.

**Comment by leppert** [comment]
Are you referring to the two instances of '.js' on line 14 of jquery.remotipart.js?
Could you provide a little more context, including which browser(s) you're using?

**Comment by sohara** [comment]
Yes, I'm referring to the two instances on line 14. I was using both Firefox 3.6.8 and Chrome 7.0.517.41 on os x. I'm surprised i'm the only one who has run into this issue because sending a format string with a period prepended shouldn't work, should it?

**Comment by leppert** [comment]
It's not actually explicitly sending a format string. It grabs the `action` attribute of the form (for instance `/mycontroller`) and appends `.js` to it (`/mycontroller.js`) so that Rails sees it as a JS request. There's certainly a lot of room for things to go south when you're blindly working with strings but you're the first person to report a problem. What's the `action` attribute for your form look like? If there's anything you could provide along the lines of a recreate it would be greatly appreciated.

It might also be helpful if you checked out the files from this (unfinished) remotipart tutorial:
https://github.com/formasfunction/Remotipart-Tutorial
I tested it just yesterday and it should work properly with Remotipart if you boot the server and visit `/albums/new` and try creating a new album with album artwork.

**Comment by leppert** [comment]
Unable to recreate.
